/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ZipStreamer;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import ZipStreamer.data.ConsoleDataSink;

public class App {
    
	public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        if (args.length > 0) {
        	ZipReader reader = new ZipReader();
        	try {
        		List<String> extensions = new ArrayList<String>();
        		extensions.add(".csv");
				reader.processFile(args[0], new ConsoleDataSink(), extensions, "\n");
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
        }
    }
}
